{
 "title": "Hosts",
 "description": "Physical nodes dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
       "legendFormat": "CPU Busy"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used RAM Memory"
      },
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
       "legendFormat": "Used Max Mount($maxmount)"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$node\"} / node_memory_SwapTotal_bytes{instance=~\"$node\"})) * 100",
       "legendFormat": "Used SWAP"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_15m"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_Iowait"
      },
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used  (EXT4/XFS)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}-0"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-0"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_Written bytes"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_ IO time"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_Avaliable"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bps", "label": "transmit（-）/receive（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_transmit"
      }
     ]
    },
    {
     "title": "Network Sockstat",
     "type": "graph",
     "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "{{instance}}_CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_tw"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=~'$node'}",
       "legendFormat": "{{instance}}_Sockets_used"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
       "legendFormat": "{{instance}}_UDP_inuse"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_alloc"
      }
     ]
    }
   ]
  }
 ]
}